import { TokenTypes } from './TokenTypes';

export enum TextToToken{
    "double" = TokenTypes.DoubleCKeyword,
    "int" = TokenTypes.IntCKeyword,
    "void" = TokenTypes.VoidCKeyword,
    "else" = TokenTypes.ElseCKeyword,
    "if" = TokenTypes.IfCKeyword,
    "elseif" = TokenTypes.ElseIfCKeyword,
    "return" = TokenTypes.ReturnCKeyword,
    "for" = TokenTypes.ForCKeyword,
    "-" = TokenTypes.MinusCToken,
    "--" = TokenTypes.MinusMinusCToken,
    "+" = TokenTypes.PlusCToken,
    "++" = TokenTypes.PlusPlusCToken,
    "*" = TokenTypes.AsteriskCToken,
    "/" = TokenTypes.SlashCToken,
    "==" = TokenTypes.EqualsEqualsCToken, 
    "=" = TokenTypes.EqualsCToken,
    ">" = TokenTypes.GreaterThanCToken,
    "<" = TokenTypes.LessThanCToken,
    "{" = TokenTypes.OpenBraceCToken,
    "}" = TokenTypes.CloseBraceCToken,
    "(" = TokenTypes.OpenParenCToken,
    ")" = TokenTypes.CloseParenCToken,
    "." = TokenTypes.DotCToken,
    ":" = TokenTypes.ColonCToken,
    ";" = TokenTypes.SemicolonCToken,
    "," = TokenTypes.CommaCToken,
    " " = TokenTypes.WhiteSpace,
}